// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvMyAPqDM2dvpixj6a7ZNXWFjMlwSx8iQ',
    appId: '1:813412897876:web:033587b2bb0aa41a6189c1',
    messagingSenderId: '813412897876',
    projectId: 'asbuilt-app',
    authDomain: 'asbuilt-app.firebaseapp.com',
    storageBucket: 'asbuilt-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5tXSHU_bvSGzzoO1a2zJl7e-6G5IoBT8',
    appId: '1:813412897876:android:9352c7701d6b07076189c1',
    messagingSenderId: '813412897876',
    projectId: 'asbuilt-app',
    storageBucket: 'asbuilt-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvMyAPqDM2dvpixj6a7ZNXWFjMlwSx8iQ',
    appId: '1:813412897876:ios:XXXXXXXXXXXX', // ← TENS QUE OBTER ISTO
    messagingSenderId: '813412897876',
    projectId: 'asbuilt-app',
    storageBucket: 'asbuilt-app.firebasestorage.app',
    iosBundleId: 'com.example.asbuilt', // ← AJUSTAR
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvMyAPqDM2dvpixj6a7ZNXWFjMlwSx8iQ',
    appId: '1:813412897876:ios:XXXXXXXXXXXX', // ← TENS QUE OBTER ISTO
    messagingSenderId: '813412897876',
    projectId: 'asbuilt-app',
    storageBucket: 'asbuilt-app.firebasestorage.app',
    iosBundleId: 'com.example.asbuilt', // ← AJUSTAR
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvMyAPqDM2dvpixj6a7ZNXWFjMlwSx8iQ',
    appId: '1:813412897876:web:033587b2bb0aa41a6189c1',
    messagingSenderId: '813412897876',
    projectId: 'asbuilt-app',
    authDomain: 'asbuilt-app.firebaseapp.com',
    storageBucket: 'asbuilt-app.firebasestorage.app',
  );
}
