#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Excel Report Generator for As-Built Installation Reports
Generates professional Excel reports with multiple phases
"""

import sys
import json
import io

# Ensure UTF-8 encoding for stdout on Windows
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from datetime import datetime
from openpyxl.utils import get_column_letter
from openpyxl.chart import BarChart, PieChart, LineChart, DoughnutChart, Reference
from openpyxl.chart.label import DataLabelList  # ← ADICIONAR ESTA LINHA
from openpyxl.formatting.rule import ColorScaleRule, CellIsRule, DataBarRule
from openpyxl.styles import colors
from openpyxl.chart import PieChart3D  # para pizza 3D
from openpyxl.chart.series import DataPoint
from openpyxl.chart.shapes import GraphicalProperties
from openpyxl.chart.axis import ChartLines
from openpyxl.drawing.line import LineProperties

def _create_cover_sheet(wb, project_name, language='pt'):
    """
    Criar sheet de capa profissional
    """
    from datetime import datetime
    
    ws = wb.create_sheet('Capa', 0)  # Primeira sheet
    
    # Estilos
    title_font = Font(name='Arial', size=24, bold=True, color='FFFFFF')
    subtitle_font = Font(name='Arial', size=14, bold=True, color='1F4E78')
    info_font = Font(name='Arial', size=11, color='1F4E78')
    label_font = Font(name='Arial', size=10, bold=True, color='666666')
    
    title_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
    
    # Configurar larguras
    ws.column_dimensions['A'].width = 5
    ws.column_dimensions['B'].width = 20
    ws.column_dimensions['C'].width = 35
    ws.column_dimensions['D'].width = 5
    
    # ══════════════════════════════════════════════════════════════
    # LOGO/TÍTULO
    # ══════════════════════════════════════════════════════════════
    
    # Título principal (merge cells)
    ws.merge_cells('B2:C2')
    title_cell = ws['B2']
    title_cell.value = '🏗️ AS-BUILT'
    title_cell.font = Font(name='Arial', size=20, bold=True, color='1F4E78')
    title_cell.alignment = Alignment(horizontal='center', vertical='center')
    
    # Subtítulo
    ws.merge_cells('B3:C3')
    subtitle_cell = ws['B3']
    if language == 'en':
        subtitle_cell.value = 'WIND TURBINE INSTALLATION REPORT'
    else:
        subtitle_cell.value = 'RELATÓRIO DE INSTALAÇÃO DE TURBINAS'
    subtitle_cell.font = Font(name='Arial', size=12, color='666666')
    subtitle_cell.alignment = Alignment(horizontal='center', vertical='center')
    
    ws['B4'].value = '─' * 50
    ws['B4'].alignment = Alignment(horizontal='center')
    
    # ══════════════════════════════════════════════════════════════
    # INFORMAÇÕES DO PROJETO
    # ══════════════════════════════════════════════════════════════
    
    current_row = 6
    
    # Nome do Projeto (DESTAQUE)
    ws.merge_cells(f'B{current_row}:C{current_row}')
    project_cell = ws[f'B{current_row}']
    project_cell.value = project_name
    project_cell.font = Font(name='Arial', size=18, bold=True, color='FFFFFF')
    project_cell.fill = title_fill
    project_cell.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[current_row].height = 35
    
    current_row += 2
    
    # Data do Relatório
    ws[f'B{current_row}'].value = 'Data do Relatório:' if language == 'pt' else 'Report Date:'
    ws[f'B{current_row}'].font = label_font
    ws[f'C{current_row}'].value = datetime.now().strftime('%d/%m/%Y %H:%M')
    ws[f'C{current_row}'].font = info_font
    
    current_row += 1
    
    # Gerado por
    ws[f'B{current_row}'].value = 'Gerado por:' if language == 'pt' else 'Generated by:'
    ws[f'B{current_row}'].font = label_font
    ws[f'C{current_row}'].value = 'As-Built v2.0'
    ws[f'C{current_row}'].font = info_font
    
    current_row += 2
    
    # ══════════════════════════════════════════════════════════════
    # RODAPÉ
    # ══════════════════════════════════════════════════════════════
    
    footer_row = 25
    ws.merge_cells(f'B{footer_row}:C{footer_row}')
    footer_cell = ws[f'B{footer_row}']
    footer_cell.value = 'www.asbuilt.com'
    footer_cell.font = Font(name='Arial', size=9, color='999999')
    footer_cell.alignment = Alignment(horizontal='center')
    
    print(f"✓ Sheet 'Capa' criada")


def _create_executive_summary_v2(wb, project_name, data_by_phase, language='pt'):
    """
    Criar sheet de Resumo Executivo COMPLETO com estatísticas detalhadas
    FASE 3 - Versão avançada
    """
    from datetime import datetime, timedelta
    
    ws = wb.create_sheet('Resumo Executivo', 1)
    
    # ══════════════════════════════════════════════════════════════
    # ESTILOS
    # ══════════════════════════════════════════════════════════════
    header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
    header_font = Font(bold=True, color='FFFFFF', size=14)
    section_font = Font(bold=True, size=12, color='1F4E78')
    label_font = Font(bold=True, size=10, color='666666')
    value_font = Font(size=11, color='1F4E78')
    
    # Larguras
    ws.column_dimensions['A'].width = 35
    ws.column_dimensions['B'].width = 20
    ws.column_dimensions['C'].width = 15
    
    current_row = 1
    
    # ══════════════════════════════════════════════════════════════
    # HEADER
    # ══════════════════════════════════════════════════════════════
    ws.merge_cells(f'A{current_row}:C{current_row}')
    header_cell = ws[f'A{current_row}']
    header_cell.value = f"📊 RESUMO EXECUTIVO - {project_name}"
    header_cell.font = header_font
    header_cell.fill = header_fill
    header_cell.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[current_row].height = 30
    
    current_row += 2
    
    # ══════════════════════════════════════════════════════════════
    # 1. ESTATÍSTICAS GERAIS
    # ══════════════════════════════════════════════════════════════
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    ws[f'A{current_row}'].value = '📈 ESTATÍSTICAS GERAIS'
    ws[f'A{current_row}'].font = section_font
    current_row += 1
    
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    # Contar turbinas
    turbinas_set = set()
    instaladas = 0
    em_instalacao = 0
    planejadas = 0
    
    for phase_key, phase_data in data_by_phase.items():
        if phase_key in ['gruasPads', 'gruasGerais']:
            continue
        for item in (phase_data or []):
            if 'turbinaId' in item:
                turbina_id = item.get('turbinaId')
                turbinas_set.add(turbina_id)
    
    # Re-contar com lógica correta
    turbinas_status = {}
    for phase_data in data_by_phase.values():
        for item in (phase_data or []):
            if 'turbinaId' in item:
                turbina_id = item.get('turbinaId')
                if item.get('dataFim'):
                    turbinas_status[turbina_id] = 'instalada'
                elif item.get('dataInicio') and turbinas_status.get(turbina_id) != 'instalada':
                    turbinas_status[turbina_id] = 'em_instalacao'
                elif turbina_id not in turbinas_status:
                    turbinas_status[turbina_id] = 'planejada'
    
    instaladas = sum(1 for status in turbinas_status.values() if status == 'instalada')
    em_instalacao = sum(1 for status in turbinas_status.values() if status == 'em_instalacao')
    planejadas = sum(1 for status in turbinas_status.values() if status == 'planejada')
    total_turbinas = len(turbinas_set)
    
    # Total de Turbinas
    ws[f'A{current_row}'].value = 'Total de Turbinas:' if language == 'pt' else 'Total Turbines:'
    ws[f'A{current_row}'].font = label_font
    ws[f'B{current_row}'].value = total_turbinas
    ws[f'B{current_row}'].font = Font(size=14, bold=True, color='1F4E78')
    ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
    current_row += 1
    
    # Turbinas Instaladas
    perc_instaladas = (instaladas / total_turbinas * 100) if total_turbinas > 0 else 0
    ws[f'A{current_row}'].value = 'Turbinas Instaladas:' if language == 'pt' else 'Installed Turbines:'
    ws[f'A{current_row}'].font = label_font
    ws[f'B{current_row}'].value = instaladas
    ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
    ws[f'C{current_row}'].value = f'{perc_instaladas:.0f}%'
    ws[f'C{current_row}'].font = Font(bold=True, color='008000')
    ws[f'C{current_row}'].alignment = Alignment(horizontal='center')
    current_row += 1
    
    # Em Instalação
    perc_em_instalacao = (em_instalacao / total_turbinas * 100) if total_turbinas > 0 else 0
    ws[f'A{current_row}'].value = 'Em Instalação:' if language == 'pt' else 'In Progress:'
    ws[f'A{current_row}'].font = label_font
    ws[f'B{current_row}'].value = em_instalacao
    ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
    ws[f'C{current_row}'].value = f'{perc_em_instalacao:.0f}%'
    ws[f'C{current_row}'].font = Font(bold=True, color='FF8C00')
    ws[f'C{current_row}'].alignment = Alignment(horizontal='center')
    current_row += 1
    
    # Planejadas
    perc_planejadas = (planejadas / total_turbinas * 100) if total_turbinas > 0 else 0
    ws[f'A{current_row}'].value = 'Planejadas:' if language == 'pt' else 'Planned:'
    ws[f'A{current_row}'].font = label_font
    ws[f'B{current_row}'].value = planejadas
    ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
    ws[f'C{current_row}'].value = f'{perc_planejadas:.0f}%'
    ws[f'C{current_row}'].font = Font(bold=True, color='999999')
    ws[f'C{current_row}'].alignment = Alignment(horizontal='center')
    current_row += 2
    
    # ══════════════════════════════════════════════════════════════
    # 2. PROGRESSO POR FASE
    # ══════════════════════════════════════════════════════════════
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    ws[f'A{current_row}'].value = '🎯 PROGRESSO POR FASE'
    ws[f'A{current_row}'].font = section_font
    current_row += 1
    
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    phase_names = {
        'pt': {
            'recepcao': 'Receção',
            'preparacao': 'Preparação',
            'preAssemblagem': 'Pré-Assemblagem',
            'assemblagem': 'Assemblagem',
            'torqueTensioning': 'Torque & Tensioning',
            'torqueTensionamento': 'Torque & Tensioning',
            'fasesFinais': 'Fases Finais',
        },
        'en': {
            'recepcao': 'Reception',
            'preparacao': 'Preparation',
            'preAssemblagem': 'Pre-Assembly',
            'assemblagem': 'Assembly',
            'torqueTensioning': 'Torque & Tensioning',
            'torqueTensionamento': 'Torque & Tensioning',
            'fasesFinais': 'Final Phases',
        }
    }
    
    for phase_key, phase_data in data_by_phase.items():
        if phase_key in ['gruasPads', 'gruasGerais']:
            continue
            
        phase_name = phase_names.get(language, phase_names['pt']).get(phase_key, phase_key)
        total = len(phase_data) if phase_data else 0
        completed = sum(1 for item in phase_data if item.get('dataFim')) if phase_data else 0
        percentage = (completed / total * 100) if total > 0 else 0
        
        ws[f'A{current_row}'].value = f'{phase_name}:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{completed}/{total}'
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        ws[f'C{current_row}'].value = f'{percentage:.0f}%'
        ws[f'C{current_row}'].alignment = Alignment(horizontal='center')
        
        # Cor condicional
        if percentage >= 100:
            ws[f'C{current_row}'].font = Font(bold=True, color='008000')
        elif percentage >= 50:
            ws[f'C{current_row}'].font = Font(bold=True, color='FF8C00')
        else:
            ws[f'C{current_row}'].font = Font(bold=True, color='FF0000')
        
        current_row += 1
    
    current_row += 1
    
    # ══════════════════════════════════════════════════════════════
    # 3. TIMELINE
    # ══════════════════════════════════════════════════════════════
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    ws[f'A{current_row}'].value = '📅 TIMELINE DO PROJETO'
    ws[f'A{current_row}'].font = section_font
    current_row += 1
    
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    # Calcular datas
    all_dates = []
    for phase_data in data_by_phase.values():
        for item in (phase_data or []):
            if item.get('dataInicio'):
                try:
                    date_str = item.get('dataInicio')
                    # Tentar parsear diferentes formatos
                    for fmt in ['%d/%m/%Y', '%Y-%m-%d', '%d-%m-%Y']:
                        try:
                            date_obj = datetime.strptime(date_str, fmt)
                            all_dates.append(date_obj)
                            break
                        except:
                            continue
                except:
                    pass
            if item.get('dataFim'):
                try:
                    date_str = item.get('dataFim')
                    for fmt in ['%d/%m/%Y', '%Y-%m-%d', '%d-%m-%Y']:
                        try:
                            date_obj = datetime.strptime(date_str, fmt)
                            all_dates.append(date_obj)
                            break
                        except:
                            continue
                except:
                    pass
    
    if all_dates:
        data_inicio = min(all_dates)
        data_atual = datetime.now()
        dias_decorridos = (data_atual - data_inicio).days
        
        # Data Início
        ws[f'A{current_row}'].value = 'Data Início:' if language == 'pt' else 'Start Date:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = data_inicio.strftime('%d/%m/%Y')
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Data Atual
        ws[f'A{current_row}'].value = 'Data Atual:' if language == 'pt' else 'Current Date:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = data_atual.strftime('%d/%m/%Y')
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Dias Decorridos
        ws[f'A{current_row}'].value = 'Dias Decorridos:' if language == 'pt' else 'Days Elapsed:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = dias_decorridos
        ws[f'B{current_row}'].font = Font(size=12, bold=True, color='1F4E78')
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Progresso Real
        progresso_real = (instaladas / total_turbinas * 100) if total_turbinas > 0 else 0
        ws[f'A{current_row}'].value = 'Progresso Real:' if language == 'pt' else 'Actual Progress:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{progresso_real:.0f}%'
        ws[f'B{current_row}'].font = Font(size=12, bold=True, color='1F4E78')
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Progresso Esperado (assumindo linear)
        progresso_esperado = min(100, (dias_decorridos / 90) * 100) if dias_decorridos > 0 else 0
        ws[f'A{current_row}'].value = 'Progresso Esperado:' if language == 'pt' else 'Expected Progress:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{progresso_esperado:.0f}%'
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Status
        if progresso_real > progresso_esperado + 10:
            status = '✅ ADIANTADO' if language == 'pt' else '✅ AHEAD'
            status_color = '008000'
        elif progresso_real < progresso_esperado - 10:
            status = '⚠️ ATRASADO' if language == 'pt' else '⚠️ DELAYED'
            status_color = 'FF0000'
        else:
            status = '➡️ NO PRAZO' if language == 'pt' else '➡️ ON TIME'
            status_color = 'FF8C00'
        
        ws[f'A{current_row}'].value = 'STATUS:' if language == 'pt' else 'STATUS:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = status
        ws[f'B{current_row}'].font = Font(size=12, bold=True, color=status_color)
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 2
    
    # ══════════════════════════════════════════════════════════════
    # 4. ESTATÍSTICAS DE GRUAS
    # ══════════════════════════════════════════════════════════════
    if 'gruasPads' in data_by_phase or 'gruasGerais' in data_by_phase:
        ws[f'A{current_row}'].value = '═══════════════════════════════════'
        current_row += 1
        
        ws[f'A{current_row}'].value = '🏗️ ESTATÍSTICAS DE GRUAS'
        ws[f'A{current_row}'].font = section_font
        current_row += 1
        
        ws[f'A{current_row}'].value = '═══════════════════════════════════'
        current_row += 1
        
        total_horas_trabalho = 0
        total_horas_paragem = 0
        total_atividades = 0
        
        for gruas_key in ['gruasPads', 'gruasGerais']:
            if gruas_key in data_by_phase:
                gruas_data = data_by_phase[gruas_key]
                for item in (gruas_data or []):
                    total_atividades += 1
                    tipo = item.get('tipo', '')
                    duracao_str = item.get('duracao', '0h')
                    
                    # Parsear duração
                    try:
                        if 'h' in duracao_str:
                            horas = float(duracao_str.replace('h', '').strip())
                            if tipo == 'trabalho':
                                total_horas_trabalho += horas
                            elif tipo == 'paragem':
                                total_horas_paragem += horas
                    except:
                        pass
        
        total_horas = total_horas_trabalho + total_horas_paragem
        perc_paragem = (total_horas_paragem / total_horas * 100) if total_horas > 0 else 0
        eficiencia = 100 - perc_paragem
        
        # Total Horas Trabalho
        ws[f'A{current_row}'].value = 'Total Horas Trabalho:' if language == 'pt' else 'Total Work Hours:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{total_horas_trabalho:.0f}h'
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Total Paragens
        ws[f'A{current_row}'].value = 'Total Paragens:' if language == 'pt' else 'Total Stoppages:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{total_horas_paragem:.0f}h'
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        ws[f'C{current_row}'].value = f'({perc_paragem:.1f}%)'
        ws[f'C{current_row}'].font = Font(color='FF0000')
        ws[f'C{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Eficiência
        ws[f'A{current_row}'].value = 'Eficiência:' if language == 'pt' else 'Efficiency:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{eficiencia:.1f}%'
        ws[f'B{current_row}'].font = Font(size=12, bold=True, color='008000')
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 2
    
    # ══════════════════════════════════════════════════════════════
    # 5. KPIs PRINCIPAIS
    # ══════════════════════════════════════════════════════════════
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    ws[f'A{current_row}'].value = '📊 KPIs PRINCIPAIS'
    ws[f'A{current_row}'].font = section_font
    current_row += 1
    
    ws[f'A{current_row}'].value = '═══════════════════════════════════'
    current_row += 1
    
    # Turbinas/Semana
    if all_dates and dias_decorridos > 0:
        semanas = dias_decorridos / 7
        turbinas_por_semana = instaladas / semanas if semanas > 0 else 0
        
        ws[f'A{current_row}'].value = 'Turbinas/Semana:' if language == 'pt' else 'Turbines/Week:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{turbinas_por_semana:.1f}'
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
        
        # Dias Médios/Turbina
        dias_por_turbina = dias_decorridos / instaladas if instaladas > 0 else 0
        ws[f'A{current_row}'].value = 'Dias Médios/Turbina:' if language == 'pt' else 'Avg Days/Turbine:'
        ws[f'A{current_row}'].font = label_font
        ws[f'B{current_row}'].value = f'{dias_por_turbina:.1f}'
        ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
        current_row += 1
    
    # Taxa de Conclusão
    taxa_conclusao = (instaladas / total_turbinas * 100) if total_turbinas > 0 else 0
    ws[f'A{current_row}'].value = 'Taxa de Conclusão:' if language == 'pt' else 'Completion Rate:'
    ws[f'A{current_row}'].font = label_font
    ws[f'B{current_row}'].value = f'{taxa_conclusao:.0f}%'
    ws[f'B{current_row}'].font = Font(size=12, bold=True, color='1F4E78')
    ws[f'B{current_row}'].alignment = Alignment(horizontal='center')
    
    print(f"✓ Resumo Executivo COMPLETO criado")


def _add_project_header(ws, project_name, sheet_name, language='pt'):
    """
    Adicionar header com informações do projeto em cada sheet
    """
    from datetime import datetime
    
    # Inserir 3 linhas no topo
    ws.insert_rows(1, 3)
    
    # Merge cells para o header
    ws.merge_cells('A1:G1')
    ws.merge_cells('A2:G2')
    
    # Header principal
    header_cell = ws['A1']
    header_cell.value = f"📁 Projeto: {project_name}"
    header_cell.font = Font(name='Arial', size=12, bold=True, color='FFFFFF')
    header_cell.fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
    header_cell.alignment = Alignment(horizontal='left', vertical='center')
    ws.row_dimensions[1].height = 22
    
    # Sub-header com data
    subheader_cell = ws['A2']
    date_str = datetime.now().strftime('%d/%m/%Y %H:%M')
    subheader_cell.value = f"📊 {sheet_name}  •  Gerado em: {date_str}" if language == 'pt' else f"📊 {sheet_name}  •  Generated: {date_str}"
    subheader_cell.font = Font(name='Arial', size=9, color='666666')
    subheader_cell.alignment = Alignment(horizontal='left', vertical='center')
    ws.row_dimensions[2].height = 18
    
    # Linha vazia
    ws.row_dimensions[3].height = 5


def _add_footer(ws, language='pt'):
    """
    Adicionar rodapé profissional
    """
    last_row = ws.max_row + 2
    
    ws.merge_cells(f'A{last_row}:G{last_row}')
    footer_cell = ws[f'A{last_row}']
    footer_cell.value = '─' * 80
    footer_cell.alignment = Alignment(horizontal='center')
    footer_cell.font = Font(color='CCCCCC')
    
    last_row += 1
    
    ws.merge_cells(f'A{last_row}:G{last_row}')
    footer_cell = ws[f'A{last_row}']
    from datetime import datetime
    footer_text = f"Gerado por As-Built v2.0  •  {datetime.now().strftime('%d/%m/%Y %H:%M')}  •  www.asbuilt.com"
    if language == 'en':
        footer_text = f"Generated by As-Built v2.0  •  {datetime.now().strftime('%d/%m/%Y %H:%M')}  •  www.asbuilt.com"
    
    footer_cell.value = footer_text
    footer_cell.alignment = Alignment(horizontal='center')
    footer_cell.font = Font(size=8, color='999999')


def _create_dashboard_v3(wb, project_name, data_by_phase, language='pt'):
    """
    Criar dashboard visual COMPLETO com todos os gráficos
    FASE 3 - Versão expandida com Timeline + Gruas + KPIs
    """
    from datetime import datetime
    from collections import defaultdict
    
    ws = wb.create_sheet('Dashboard', 2)

    # Estilos
    header_fill = PatternFill(start_color='1F4E78', end_color='1F4E78', fill_type='solid')
    header_font = Font(bold=True, color='FFFFFF', size=12)

    # Header principal
    ws.merge_cells('A1:P1')
    header_cell = ws['A1']
    header_cell.value = f'📊 Dashboard - {project_name}'
    header_cell.font = header_font
    header_cell.fill = header_fill
    header_cell.alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[1].height = 25

    # ══════════════════════════════════════════════════════════════
    # SEÇÃO 1: PROGRESSO POR FASE (ESQUERDA)
    # ══════════════════════════════════════════════════════════════
    ws['A3'].value = 'PROGRESSO POR FASE' if language == 'pt' else 'PROGRESS BY PHASE'
    ws['A3'].font = Font(size=14, bold=True, color='1F4E78')

    # Headers
    headers = ['Fase', 'Total', 'Concluídos', '%'] if language == 'pt' else ['Phase', 'Total', 'Completed', '%']
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=5, column=col_idx)
        cell.value = header
        cell.font = Font(bold=True)
        cell.fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')
        cell.alignment = Alignment(horizontal='center')

    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 10
    ws.column_dimensions['C'].width = 12
    ws.column_dimensions['D'].width = 10

    phase_names = {
        'pt': {
            'recepcao': 'Receção',
            'preparacao': 'Preparação',
            'preAssemblagem': 'Pré-Assemblagem',
            'assemblagem': 'Assemblagem',
            'torqueTensioning': 'Torque',
            'torqueTensionamento': 'Torque',
            'fasesFinais': 'Fases Finais',
        },
        'en': {
            'recepcao': 'Reception',
            'preparacao': 'Preparation',
            'preAssemblagem': 'Pre-Assembly',
            'assemblagem': 'Assembly',
            'torqueTensioning': 'Torque',
            'torqueTensionamento': 'Torque',
            'fasesFinais': 'Final Phases',
        }
    }

    current_row = 6
    data_start_row = 6

    for phase_key, phase_data in data_by_phase.items():
        if phase_key in ['gruasPads', 'gruasGerais']:
            continue

        phase_name = phase_names.get(language, phase_names['pt']).get(phase_key, phase_key)
        total = len(phase_data) if phase_data else 0
        completed = sum(1 for item in phase_data if item.get('dataFim')) if phase_data else 0
        percentage = (completed / total * 100) if total > 0 else 0.0

        ws.cell(row=current_row, column=1, value=phase_name)
        ws.cell(row=current_row, column=2, value=total).alignment = Alignment(horizontal='center')
        ws.cell(row=current_row, column=3, value=completed).alignment = Alignment(horizontal='center')
        
        c = ws.cell(row=current_row, column=4, value=float(f"{percentage:.1f}"))
        c.number_format = '0.0'
        c.alignment = Alignment(horizontal='center')

        current_row += 1

    data_end_row = current_row - 1

    # GRÁFICO 1: BARRAS - PROGRESSO POR FASE
    if data_end_row >= data_start_row:
        bar_chart = BarChart()
        bar_chart.type = "col"
        bar_chart.style = 10
        bar_chart.title = None
        bar_chart.y_axis.scaling.min = 0
        bar_chart.y_axis.scaling.max = 100
        bar_chart.y_axis.title = None
        bar_chart.x_axis.title = None

        data_ref = Reference(ws, min_col=4, min_row=5, max_row=data_end_row)
        cats_ref = Reference(ws, min_col=1, min_row=6, max_row=data_end_row)

        bar_chart.add_data(data_ref, titles_from_data=True)
        bar_chart.set_categories(cats_ref)

        bar_chart.dataLabels = DataLabelList()
        bar_chart.dataLabels.showVal = True
        bar_chart.dataLabels.showSerName = False
        bar_chart.dataLabels.showCatName = False
        bar_chart.dataLabels.showLegendKey = False

        bar_chart.legend.position = 'b'
        bar_chart.width = 14
        bar_chart.height = 9

        ws.add_chart(bar_chart, 'F5')

    # ══════════════════════════════════════════════════════════════
    # SEÇÃO 2: STATUS DAS TURBINAS
    # ══════════════════════════════════════════════════════════════
    status_row = data_end_row + 7
    ws[f'A{status_row}'].value = 'STATUS DAS TURBINAS' if language == 'pt' else 'TURBINE STATUS'
    ws[f'A{status_row}'].font = Font(size=14, bold=True, color='1F4E78')

    status_row += 2

    # Contar turbinas
    total_turbinas = 0
    instaladas = 0
    em_instalacao = 0
    planejadas = 0

    for phase_data in data_by_phase.values():
        for item in (phase_data or []):
            if 'turbinaId' in item:
                total_turbinas += 1
                if item.get('dataFim'):
                    instaladas += 1
                elif item.get('dataInicio'):
                    em_instalacao += 1
                else:
                    planejadas += 1

    ws.cell(row=status_row, column=1, value='Status')
    ws.cell(row=status_row, column=1).font = Font(bold=True)
    ws.cell(row=status_row, column=1).fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')

    ws.cell(row=status_row, column=2, value='Quantidade' if language == 'pt' else 'Quantity')
    ws.cell(row=status_row, column=2).font = Font(bold=True)
    ws.cell(row=status_row, column=2).fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')
    ws.cell(row=status_row, column=2).alignment = Alignment(horizontal='center')

    status_data_start = status_row + 1

    ws.cell(row=status_row + 1, column=1, value='Instaladas' if language == 'pt' else 'Installed')
    ws.cell(row=status_row + 1, column=2, value=instaladas).alignment = Alignment(horizontal='center')

    ws.cell(row=status_row + 2, column=1, value='Em Instalação' if language == 'pt' else 'In Progress')
    ws.cell(row=status_row + 2, column=2, value=em_instalacao).alignment = Alignment(horizontal='center')

    ws.cell(row=status_row + 3, column=1, value='Planejadas' if language == 'pt' else 'Planned')
    ws.cell(row=status_row + 3, column=2, value=planejadas).alignment = Alignment(horizontal='center')

    status_data_end = status_row + 5

    # GRÁFICO 2: PIZZA - STATUS DAS TURBINAS
    pie_chart = PieChart()
    pie_chart.title = None
    pie_chart.legend.position = 'b'

    data_ref = Reference(ws, min_col=2, min_row=status_row, max_row=status_data_end)
    labels_ref = Reference(ws, min_col=1, min_row=status_data_start, max_row=status_data_end)

    pie_chart.add_data(data_ref, titles_from_data=True)
    pie_chart.set_categories(labels_ref)

    pie_chart.dataLabels = DataLabelList()
    pie_chart.dataLabels.showPercent = True
    pie_chart.dataLabels.showSerName = False
    pie_chart.dataLabels.showCatName = True
    pie_chart.dataLabels.showVal = False

    pie_chart.width = 14
    pie_chart.height = 9

    ws.add_chart(pie_chart, f'F{status_row + 6}')

    # ══════════════════════════════════════════════════════════════
    # SEÇÃO 3: TIMELINE DE INSTALAÇÃO (NOVO!)
    # ══════════════════════════════════════════════════════════════
    timeline_row = status_data_end + 20
    ws[f'A{timeline_row}'].value = 'TIMELINE DE INSTALAÇÃO' if language == 'pt' else 'INSTALLATION TIMELINE'
    ws[f'A{timeline_row}'].font = Font(size=14, bold=True, color='1F4E78')

    timeline_row += 2

    # Agrupar turbinas por data de conclusão
    timeline_data = defaultdict(int)
    
    for phase_data in data_by_phase.values():
        for item in (phase_data or []):
            if item.get('dataFim'):
                date_str = item.get('dataFim')
                try:
                    # Tentar parsear data
                    for fmt in ['%d/%m/%Y', '%Y-%m-%d', '%d-%m-%Y']:
                        try:
                            date_obj = datetime.strptime(date_str, fmt)
                            week_key = date_obj.strftime('%Y-W%W')  # Ano-Semana
                            timeline_data[week_key] += 1
                            break
                        except:
                            continue
                except:
                    pass

    # Se temos dados de timeline
    if timeline_data:
        # Ordenar por data
        sorted_timeline = sorted(timeline_data.items())
        
        # Headers
        ws.cell(row=timeline_row, column=1, value='Período' if language == 'pt' else 'Period')
        ws.cell(row=timeline_row, column=1).font = Font(bold=True)
        ws.cell(row=timeline_row, column=1).fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')
        
        ws.cell(row=timeline_row, column=2, value='Turbinas Instaladas' if language == 'pt' else 'Turbines Installed')
        ws.cell(row=timeline_row, column=2).font = Font(bold=True)
        ws.cell(row=timeline_row, column=2).fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')
        
        timeline_data_start = timeline_row + 3
        
        # Dados
        acumulado = 0
        for idx, (period, count) in enumerate(sorted_timeline, start=1):
            acumulado += count
            ws.cell(row=timeline_row + idx, column=1, value=f'Semana {idx}')
            ws.cell(row=timeline_row + idx, column=2, value=acumulado).alignment = Alignment(horizontal='center')
        
        timeline_data_end = timeline_row + len(sorted_timeline)
        
        # GRÁFICO 3: LINHA - TIMELINE (NOVO!)
        line_chart = LineChart()
        line_chart.title = None
        line_chart.style = 10
        line_chart.y_axis.title = 'Turbinas' if language == 'pt' else 'Turbines'
        line_chart.x_axis.title = None

        data_ref = Reference(ws, min_col=2, min_row=timeline_data_start - 1, max_row=timeline_data_end)
        cats_ref = Reference(ws, min_col=1, min_row=timeline_data_start, max_row=timeline_data_end)

        line_chart.add_data(data_ref, titles_from_data=True)
        line_chart.set_categories(cats_ref)
        
        line_chart.legend.position = 'b'
        line_chart.width = 14
        line_chart.height = 9

        ws.add_chart(line_chart, f'F{timeline_row}')

    # ══════════════════════════════════════════════════════════════
    # SEÇÃO 4: GRUAS - TRABALHO VS PARAGENS (NOVO!)
    # ══════════════════════════════════════════════════════════════
    gruas_row = timeline_row + 20
    
    if 'gruasPads' in data_by_phase or 'gruasGerais' in data_by_phase:
        ws[f'A{gruas_row}'].value = 'GRUAS - TRABALHO vs PARAGENS' if language == 'pt' else 'CRANES - WORK vs STOPPAGES'
        ws[f'A{gruas_row}'].font = Font(size=14, bold=True, color='1F4E78')

        gruas_row += 2

        # Calcular horas
        total_trabalho = 0
        total_paragens = 0

        for gruas_key in ['gruasPads', 'gruasGerais']:
            if gruas_key in data_by_phase:
                for item in (data_by_phase[gruas_key] or []):
                    tipo = item.get('tipo', '')
                    duracao_str = item.get('duracao', '0h')
                    
                    try:
                        if 'h' in duracao_str:
                            horas = float(duracao_str.replace('h', '').strip())
                            if tipo == 'trabalho':
                                total_trabalho += horas
                            elif tipo == 'paragem':
                                total_paragens += horas
                    except:
                        pass

        # Headers
        ws.cell(row=gruas_row, column=1, value='Tipo' if language == 'pt' else 'Type')
        ws.cell(row=gruas_row, column=1).font = Font(bold=True)
        ws.cell(row=gruas_row, column=1).fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')
        
        ws.cell(row=gruas_row, column=2, value='Horas' if language == 'pt' else 'Hours')
        ws.cell(row=gruas_row, column=2).font = Font(bold=True)
        ws.cell(row=gruas_row, column=2).fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')

        gruas_data_start = gruas_row + 1

        ws.cell(row=gruas_row + 1, column=1, value='Trabalho' if language == 'pt' else 'Work')
        ws.cell(row=gruas_row + 1, column=2, value=total_trabalho).alignment = Alignment(horizontal='center')

        ws.cell(row=gruas_row + 2, column=1, value='Paragens' if language == 'pt' else 'Stoppages')
        ws.cell(row=gruas_row + 2, column=2, value=total_paragens).alignment = Alignment(horizontal='center')

        gruas_data_end = gruas_row + 4

        # GRÁFICO 4: BARRAS - GRUAS (NOVO!)
        gruas_chart = BarChart()
        gruas_chart.type = "col"
        gruas_chart.style = 11
        gruas_chart.title = None
        gruas_chart.y_axis.title = 'Horas' if language == 'pt' else 'Hours'
        gruas_chart.x_axis.title = None

        data_ref = Reference(ws, min_col=2, min_row=gruas_row, max_row=gruas_data_end)
        cats_ref = Reference(ws, min_col=1, min_row=gruas_data_start, max_row=gruas_data_end)

        gruas_chart.add_data(data_ref, titles_from_data=True)
        gruas_chart.set_categories(cats_ref)

        gruas_chart.dataLabels = DataLabelList()
        gruas_chart.dataLabels.showVal = True

        gruas_chart.legend.position = 'b'
        gruas_chart.width = 14
        gruas_chart.height = 9

        ws.add_chart(gruas_chart, f'F{gruas_row}')

    # ══════════════════════════════════════════════════════════════
    # SEÇÃO 5: TABELA DE KPIs COM ÍCONES (NOVO!)
    # ══════════════════════════════════════════════════════════════
    kpi_row = gruas_row + 20
    ws[f'A{kpi_row}'].value = 'KPIs PRINCIPAIS' if language == 'pt' else 'KEY PERFORMANCE INDICATORS'
    ws[f'A{kpi_row}'].font = Font(size=14, bold=True, color='1F4E78')

    kpi_row += 2

    # Headers
    kpi_headers = ['KPI', 'Valor', 'Meta', 'Status']
    for col_idx, header in enumerate(kpi_headers, start=1):
        cell = ws.cell(row=kpi_row, column=col_idx)
        cell.value = header
        cell.font = Font(bold=True)
        cell.fill = PatternFill(start_color='E7E6E6', end_color='E7E6E6', fill_type='solid')
        cell.alignment = Alignment(horizontal='center')

    kpi_row += 1

    # KPI 1: Taxa de Conclusão
    taxa_conclusao = (instaladas / total_turbinas * 100) if total_turbinas > 0 else 0
    meta_conclusao = 70
    
    ws.cell(row=kpi_row, column=1, value='Taxa de Conclusão' if language == 'pt' else 'Completion Rate')
    ws.cell(row=kpi_row, column=2, value=f'{taxa_conclusao:.0f}%').alignment = Alignment(horizontal='center')
    ws.cell(row=kpi_row, column=3, value=f'{meta_conclusao}%').alignment = Alignment(horizontal='center')
    
    if taxa_conclusao >= meta_conclusao:
        ws.cell(row=kpi_row, column=4, value='✅')
        ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='008000')
    elif taxa_conclusao >= meta_conclusao * 0.8:
        ws.cell(row=kpi_row, column=4, value='⚠️')
        ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='FFA500')
    else:
        ws.cell(row=kpi_row, column=4, value='❌')
        ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='FF0000')
    ws.cell(row=kpi_row, column=4).alignment = Alignment(horizontal='center')
    
    kpi_row += 1

    # KPI 2: Eficiência de Gruas
    if total_trabalho + total_paragens > 0:
        eficiencia_gruas = (total_trabalho / (total_trabalho + total_paragens) * 100)
        meta_eficiencia = 95
        
        ws.cell(row=kpi_row, column=1, value='Eficiência Gruas' if language == 'pt' else 'Crane Efficiency')
        ws.cell(row=kpi_row, column=2, value=f'{eficiencia_gruas:.1f}%').alignment = Alignment(horizontal='center')
        ws.cell(row=kpi_row, column=3, value=f'{meta_eficiencia}%').alignment = Alignment(horizontal='center')
        
        if eficiencia_gruas >= meta_eficiencia:
            ws.cell(row=kpi_row, column=4, value='✅')
            ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='008000')
        elif eficiencia_gruas >= meta_eficiencia * 0.9:
            ws.cell(row=kpi_row, column=4, value='⚠️')
            ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='FFA500')
        else:
            ws.cell(row=kpi_row, column=4, value='❌')
            ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='FF0000')
        ws.cell(row=kpi_row, column=4).alignment = Alignment(horizontal='center')
        
        kpi_row += 1

    # KPI 3: Progresso Geral
    progresso_geral = sum(
        (sum(1 for item in phase_data if item.get('dataFim')) / len(phase_data) * 100) if phase_data else 0
        for phase_key, phase_data in data_by_phase.items()
        if phase_key not in ['gruasPads', 'gruasGerais']
    ) / max(len([k for k in data_by_phase.keys() if k not in ['gruasPads', 'gruasGerais']]), 1)
    
    meta_progresso = 60
    
    ws.cell(row=kpi_row, column=1, value='Progresso Geral' if language == 'pt' else 'Overall Progress')
    ws.cell(row=kpi_row, column=2, value=f'{progresso_geral:.0f}%').alignment = Alignment(horizontal='center')
    ws.cell(row=kpi_row, column=3, value=f'{meta_progresso}%').alignment = Alignment(horizontal='center')
    
    if progresso_geral >= meta_progresso:
        ws.cell(row=kpi_row, column=4, value='✅')
        ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='008000')
    elif progresso_geral >= meta_progresso * 0.85:
        ws.cell(row=kpi_row, column=4, value='⚠️')
        ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='FFA500')
    else:
        ws.cell(row=kpi_row, column=4, value='❌')
        ws.cell(row=kpi_row, column=4).font = Font(size=12, bold=True, color='FF0000')
    ws.cell(row=kpi_row, column=4).alignment = Alignment(horizontal='center')

    print("✓ Dashboard COMPLETO criado com 4 gráficos + KPIs")

def _add_data_bars(ws, data_start_row, data_end_row, col_idx):
    """
    Adicionar barras de dados (data bars) para visualização rápida
    """
    # Criar data bar (azul)
    data_bar = DataBarRule(
        start_type='num', start_value=0,
        end_type='num', end_value=100,
        color='4472C4'
    )
    
    # Aplicar
    range_string = f'{chr(64 + col_idx)}{data_start_row}:{chr(64 + col_idx)}{data_end_row}'
    ws.conditional_formatting.add(range_string, data_bar)
    
    print(f"✓ Data bars aplicadas em {range_string}")


def _add_auto_filters(ws, header_row, last_col):
    """
    Adicionar auto-filtros às tabelas
    """
    # Definir range para filtro
    ws.auto_filter.ref = f'A{header_row}:{chr(64 + last_col)}{ws.max_row}'
    
    # Freeze panes (congelar primeira linha)
    ws.freeze_panes = f'A{header_row + 1}'
    
    print(f"✓ Auto-filtros adicionados e panes congelados")


    # ══════════════════════════════════════════════════════════════
    # FUNÇÕES DAS SHEETS DE FASES
    # ══════════════════════════════════════════════════════════════

def _add_recepcao_sheet(wb, recepcao_data, lang='pt'):  # ✅ CORRETO! Sem indentação
    """Criar sheet de Receção"""
    sheet_name = 'Reception' if lang == 'en' else 'Receção'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers
    if lang == 'en':
        headers = ['Turbine', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Unload Date', 'Time']
    else:
        headers = ['Turbina', 'Componente', 'VUI', 'Nº Série', 'Nº Item', 'Data Descarga', 'Hora']
    
    column_widths = [15, 25, 15, 20, 15, 15, 10]
    
    # Escrever headers
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # Definir larguras
    for col_idx, width in enumerate(column_widths, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    
    # Escrever dados
    for row_idx, item in enumerate(recepcao_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('turbinaId', '')).border = border
        ws.cell(row=row_idx, column=2, value=item.get('componentId', '')).border = border
        ws.cell(row=row_idx, column=3, value=item.get('vui', '')).border = border
        ws.cell(row=row_idx, column=4, value=item.get('serialNumber', '')).border = border
        ws.cell(row=row_idx, column=5, value=item.get('itemNumber', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('dataDescarga', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('horaDescarga', '')).border = border
    
    print(f"✓ Sheet '{sheet_name}' criada")


def _add_preparacao_sheet(wb, preparacao_data, lang='pt'):
    """Criar sheet de Preparação"""
    sheet_name = 'Preparation' if lang == 'en' else 'Preparação'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers
    if lang == 'en':
        headers = ['Turbine', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Start Date', 'Start Time', 'End Date', 'End Time']
    else:
        headers = ['Turbina', 'Componente', 'VUI', 'Nº Série', 'Nº Item', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim']
    
    column_widths = [15, 25, 15, 20, 15, 15, 12, 15, 12]
    
    # Escrever headers
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # Definir larguras
    for col_idx, width in enumerate(column_widths, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    
    # Escrever dados
    for row_idx, item in enumerate(preparacao_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('turbinaId', '')).border = border
        ws.cell(row=row_idx, column=2, value=item.get('componentId', '')).border = border
        ws.cell(row=row_idx, column=3, value=item.get('vui', '')).border = border
        ws.cell(row=row_idx, column=4, value=item.get('serialNumber', '')).border = border
        ws.cell(row=row_idx, column=5, value=item.get('itemNumber', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('dataInicio', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('horaInicio', '')).border = border
        ws.cell(row=row_idx, column=8, value=item.get('dataFim', '')).border = border
        ws.cell(row=row_idx, column=9, value=item.get('horaFim', '')).border = border
    
    print(f"✓ Sheet '{sheet_name}' criada")


def _add_pre_assemblagem_sheet(wb, pre_data, lang='pt'):
    """Criar sheet de Pré-Assemblagem"""
    sheet_name = 'Pre-Assembly' if lang == 'en' else 'Pré-Assemblagem'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers
    if lang == 'en':
        headers = ['Turbine', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Start Date', 'Start Time', 'End Date', 'End Time']
    else:
        headers = ['Turbina', 'Componente', 'VUI', 'Nº Série', 'Nº Item', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim']
    
    column_widths = [15, 25, 15, 20, 15, 15, 12, 15, 12]
    
    # Escrever headers
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # Definir larguras
    for col_idx, width in enumerate(column_widths, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    
    # Escrever dados
    for row_idx, item in enumerate(pre_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('turbinaId', '')).border = border
        ws.cell(row=row_idx, column=2, value=item.get('componentId', '')).border = border
        ws.cell(row=row_idx, column=3, value=item.get('vui', '')).border = border
        ws.cell(row=row_idx, column=4, value=item.get('serialNumber', '')).border = border
        ws.cell(row=row_idx, column=5, value=item.get('itemNumber', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('dataInicio', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('horaInicio', '')).border = border
        ws.cell(row=row_idx, column=8, value=item.get('dataFim', '')).border = border
        ws.cell(row=row_idx, column=9, value=item.get('horaFim', '')).border = border
    
    print(f"✓ Sheet '{sheet_name}' criada")


def _add_assemblagem_sheet(wb, assemblagem_data, lang='pt'):
    """Criar sheet de Assemblagem"""
    sheet_name = 'Assembly' if lang == 'en' else 'Assemblagem'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers
    if lang == 'en':
        headers = ['Turbine', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Start Date', 'Start Time', 'End Date', 'End Time']
    else:
        headers = ['Turbina', 'Componente', 'VUI', 'Nº Série', 'Nº Item', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim']
    
    column_widths = [15, 25, 15, 20, 15, 15, 12, 15, 12]
    
    # Escrever headers
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # Definir larguras
    for col_idx, width in enumerate(column_widths, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    
    # Escrever dados
    for row_idx, item in enumerate(assemblagem_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('turbinaId', '')).border = border
        ws.cell(row=row_idx, column=2, value=item.get('componentId', '')).border = border
        ws.cell(row=row_idx, column=3, value=item.get('vui', '')).border = border
        ws.cell(row=row_idx, column=4, value=item.get('serialNumber', '')).border = border
        ws.cell(row=row_idx, column=5, value=item.get('itemNumber', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('dataInicio', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('horaInicio', '')).border = border
        ws.cell(row=row_idx, column=8, value=item.get('dataFim', '')).border = border
        ws.cell(row=row_idx, column=9, value=item.get('horaFim', '')).border = border
    
    print(f"✓ Sheet '{sheet_name}' criada")


def _add_torque_sheet(wb, torque_data, lang='pt'):
    """Criar sheet de Torque & Tensioning"""
    sheet_name = 'Torque & Tensioning'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="FF5722", end_color="FF5722", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers
    if lang == 'en':
        headers = ['Turbine', 'Connection', 'Status', 'Progress %', 'Start Date', 'Start Time', 'End Date', 'End Time']
    else:
        headers = ['Turbina', 'Conexão', 'Status', 'Progresso %', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim']
    
    column_widths = [15, 30, 15, 12, 15, 12, 15, 12]
    
    # Escrever headers
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # Definir larguras
    for col_idx, width in enumerate(column_widths, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    
    # Escrever dados
    for row_idx, item in enumerate(torque_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('turbinaId', '')).border = border
        ws.cell(row=row_idx, column=2, value=f"{item.get('componenteOrigem', '')} → {item.get('componenteDestino', '')}").border = border
        ws.cell(row=row_idx, column=3, value=item.get('status', '')).border = border
        ws.cell(row=row_idx, column=4, value=item.get('progresso', 0)).border = border
        ws.cell(row=row_idx, column=5, value=item.get('dataInicio', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('horaInicio', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('dataFim', '')).border = border
        ws.cell(row=row_idx, column=8, value=item.get('horaFim', '')).border = border
    
    print(f"✓ Sheet '{sheet_name}' criada")


def _add_fases_finais_sheet(wb, fases_data, lang='pt'):
    """Criar sheet de Fases Finais"""
    sheet_name = 'Final Phases' if lang == 'en' else 'Fases Finais'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers
    if lang == 'en':
        headers = ['Turbine', 'Phase', 'Status', 'Start Date', 'Start Time', 'End Date', 'End Time']
    else:
        headers = ['Turbina', 'Fase', 'Status', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim']
    
    column_widths = [15, 25, 15, 15, 12, 15, 12]
    
    # Escrever headers
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # Definir larguras
    for col_idx, width in enumerate(column_widths, start=1):
        ws.column_dimensions[get_column_letter(col_idx)].width = width
    
    # Escrever dados
    for row_idx, item in enumerate(fases_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('turbinaId', '')).border = border
        ws.cell(row=row_idx, column=2, value=item.get('faseName', '')).border = border
        ws.cell(row=row_idx, column=3, value=item.get('status', '')).border = border
        ws.cell(row=row_idx, column=4, value=item.get('dataInicio', '')).border = border
        ws.cell(row=row_idx, column=5, value=item.get('horaInicio', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('dataFim', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('horaFim', '')).border = border
    
    print(f"✓ Sheet '{sheet_name}' criada")


def generate_excel_report(project_name, data_by_phase, selected_phases, output_path, language='pt'):
    """
    Gera relatório Excel com dados de instalação
    """
    print(f"\n{'='*60}")
    print(f"🚀 INICIANDO GERAÇÃO DE RELATÓRIO EXCEL - FASE 2")
    print(f"{'='*60}")
    print(f"📁 Projeto: {project_name}")
    print(f"🌍 Idioma: {language.upper()}")
    print(f"📊 Fases selecionadas: {len(selected_phases)}")
    
    wb = Workbook()
    
    # Remover sheet padrão
    if 'Sheet' in wb.sheetnames:
        wb.remove(wb['Sheet'])
    
    # ══════════════════════════════════════════════════════════════
    # FASE 1: CAPA E RESUMO EXECUTIVO
    # ══════════════════════════════════════════════════════════════
    _create_cover_sheet(wb, project_name, language)
    _create_executive_summary_v2(wb, project_name, data_by_phase, language)
    
    # ══════════════════════════════════════════════════════════════
    # 🆕 FASE 2: DASHBOARD COM GRÁFICOS
    # ══════════════════════════════════════════════════════════════
    _create_dashboard_v3(wb, project_name, data_by_phase, language)
    
    # ══════════════════════════════════════════════════════════════
    # CRIAR SHEETS DAS FASES (COM AUTO-FILTROS E FORMATAÇÃO)
    # ══════════════════════════════════════════════════════════════
    
    current_sheet_idx = 3
    
    # Processar Receção
    if 'recepcao' in selected_phases:
        recepcao_data = data_by_phase.get('recepcao')
        if recepcao_data:
            print(f"[OK] Adding 'Receção' sheet with {len(recepcao_data)} items")
            _add_recepcao_sheet(wb, recepcao_data, language)
            
            # 🆕 FASE 2: Auto-filtros e formatação
            sheet_name = 'Receção' if language == 'pt' else 'Reception'
            ws = wb[sheet_name]
            _add_project_header(ws, project_name, sheet_name, language)
            _add_auto_filters(ws, 4, 7)  # Linha 4 = header (após insert_rows), 7 colunas
            _add_footer(ws, language)
            current_sheet_idx += 1
    
    # Processar Preparação
    if 'preparacao' in selected_phases:
        preparacao_data = data_by_phase.get('preparacao')
        if preparacao_data:
            print(f"[OK] Adding 'Preparação' sheet with {len(preparacao_data)} items")
            _add_preparacao_sheet(wb, preparacao_data, language)
            
            sheet_name = 'Preparação' if language == 'pt' else 'Preparation'
            ws = wb[sheet_name]
            _add_project_header(ws, project_name, sheet_name, language)
            _add_auto_filters(ws, 4, 9)
            _add_footer(ws, language)
            current_sheet_idx += 1
    
    # Processar Pré-Assemblagem
    if 'preAssemblagem' in selected_phases:
        pre_assemblagem_data = data_by_phase.get('preAssemblagem')
        if pre_assemblagem_data:
            print(f"[OK] Adding 'Pré-Assemblagem' sheet with {len(pre_assemblagem_data)} items")
            _add_pre_assemblagem_sheet(wb, pre_assemblagem_data, language)
            
            sheet_name = 'Pré-Assemblagem' if language == 'pt' else 'Pre-Assembly'
            ws = wb[sheet_name]
            _add_project_header(ws, project_name, sheet_name, language)
            _add_auto_filters(ws, 4, 9)
            _add_footer(ws, language)
            current_sheet_idx += 1
    
    # Processar Assemblagem
    if 'assemblagem' in selected_phases:
        assemblagem_data = data_by_phase.get('assemblagem')
        if assemblagem_data:
            print(f"[OK] Adding 'Assemblagem' sheet with {len(assemblagem_data)} items")
            _add_assemblagem_sheet(wb, assemblagem_data, language)
            
            sheet_name = 'Assemblagem' if language == 'pt' else 'Assembly'
            ws = wb[sheet_name]
            _add_project_header(ws, project_name, sheet_name, language)
            # 🆕 FASE 2: Adicionar formatação condicional se houver coluna de progresso
            _add_auto_filters(ws, 4, 9)
            _add_footer(ws, language)
            current_sheet_idx += 1
    
    # Processar Torque & Tensioning
    if 'torqueTensionamento' in selected_phases:
        torque_data = data_by_phase.get('torqueTensionamento')
        if torque_data:
            print(f"[OK] Adding 'Torque & Tensioning' sheet with {len(torque_data)} items")
            _add_torque_sheet(wb, torque_data, language)
            
            sheet_name = 'Torque & Tensioning'
            ws = wb[sheet_name]
            _add_project_header(ws, project_name, sheet_name, language)
            _add_auto_filters(ws, 4, 8)
            _add_footer(ws, language)
            current_sheet_idx += 1
    
    # Processar Fases Finais
    if 'fasesFinais' in selected_phases:
        fases_data = data_by_phase.get('fasesFinais')
        if fases_data:
            print(f"[OK] Adding 'Fases Finais' sheet with {len(fases_data)} items")
            _add_fases_finais_sheet(wb, fases_data, language)
            
            sheet_name = 'Fases Finais' if language == 'pt' else 'Final Phases'
            ws = wb[sheet_name]
            _add_project_header(ws, project_name, sheet_name, language)
            _add_auto_filters(ws, 4, 7)
            _add_footer(ws, language)
            current_sheet_idx += 1
    
    # ═══════════════════════════════════════════════════════════════
    # GRUAS DE PADS
    # ═══════════════════════════════════════════════════════════════
    print(f"DEBUG: Processing 'gruasPads' - in selected_phases: {'gruasPads' in selected_phases}")
    if 'gruasPads' in selected_phases:
        pads_data = data_by_phase.get('gruasPads')
        if pads_data:
            print(f"[OK] Adding 'Gruas de Pads' sheet with {len(pads_data)} items")
            _add_gruas_pads_sheet(wb, pads_data, language)
            # 🆕 FASE 2: ADICIONAR AUTO-FILTROS E HEADER/FOOTER
            sheet_name = 'Gruas (Pads)' if language == 'pt' else 'Cranes (Pads)'
            ws_gruas = wb[sheet_name]
            _add_project_header(ws_gruas, project_name, sheet_name, language)
            _add_auto_filters(ws_gruas, 4, 12)
            _add_footer(ws_gruas, language)
        else:
            print("[WARN] 'gruasPads' selected but no data found")
    
    # ═══════════════════════════════════════════════════════════════
    # GRUAS GERAIS
    # ═══════════════════════════════════════════════════════════════
    print(f"DEBUG: Processing 'gruasGerais' - in selected_phases: {'gruasGerais' in selected_phases}")
    if 'gruasGerais' in selected_phases:
        gerais_data = data_by_phase.get('gruasGerais')
        if gerais_data:
            print(f"[OK] Adding 'Gruas Gerais' sheet with {len(gerais_data)} items")
            _add_gruas_gerais_sheet(wb, gerais_data, language)
            # 🆕 FASE 2: ADICIONAR AUTO-FILTROS E HEADER/FOOTER
            sheet_name = 'Gruas Gerais' if language == 'pt' else 'Cranes (General)'
            ws_gruas = wb[sheet_name]
            _add_project_header(ws_gruas, project_name, sheet_name, language)
            _add_auto_filters(ws_gruas, 4, 12)
            _add_footer(ws_gruas, language)
        else:
            print("[WARN] 'gruasGerais' selected but no data found")
    
    # Salvar
    wb.save(output_path)
    print(f"\n✅ Excel salvo com FASE 2 completa: {output_path}")
    print(f"   📊 Dashboard com gráficos")
    print(f"   📋 Auto-filtros em todas as sheets")
    print(f"   🎨 Formatação condicional aplicada")
    print(f"{'='*60}\n")


def _get_phase_headers(phase):
    """Retorna cabeçalhos das colunas para cada fase"""
    
    if phase == 'recepcao':
        return ['Turbina', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Data Descarga', 'Hora']
    
    elif phase in ['preparacao', 'preAssemblagem', 'assemblagem']:
        return ['Turbina', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim']
    
    elif phase == 'torqueTensionamento':
        return ['Turbina', 'Conexão', 'Torque Value', 'Torque Unit', 'Tensioning Value', 'Tensioning Unit', 'Data', 'Hora']
    
    elif phase == 'fasesFinais':
        return ['Turbina', 'Fase', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim', 'Status']
    
    return ['Turbina', 'Component', 'Data']


def _format_phase_row(phase, item):
    """Formata uma linha de dados para a fase"""
    
    if phase == 'recepcao':
        return [
            item.get('turbinaId', ''),
            item.get('componentId', ''),
            item.get('vui', ''),
            item.get('serialNumber', ''),
            item.get('itemNumber', ''),
            item.get('dataDescarga', ''),
            item.get('horaDescarga', ''),
        ]
    
    elif phase in ['preparacao', 'preAssemblagem', 'assemblagem']:
        return [
            item.get('turbinaId', ''),
            item.get('componentId', ''),
            item.get('vui', ''),
            item.get('serialNumber', ''),
            item.get('itemNumber', ''),
            item.get('dataInicio', ''),
            item.get('horaInicio', ''),
            item.get('dataFim', ''),
            item.get('horaFim', ''),
        ]
    
    elif phase == 'torqueTensionamento':
        return [
            item.get('turbinaId', ''),
            item.get('conexao', ''),
            item.get('torqueValue', ''),
            item.get('torqueUnit', ''),
            item.get('tensioningValue', ''),
            item.get('tensioningUnit', ''),
            item.get('dataExecucao', ''),
            item.get('horaExecucao', ''),
        ]
    
    elif phase == 'fasesFinais':
        return [
            item.get('turbinaId', ''),
            item.get('faseName', ''),
            item.get('dataInicio', ''),
            item.get('horaInicio', ''),
            item.get('dataFim', ''),
            item.get('horaFim', ''),
            item.get('status', ''),
        ]
    
    return [item.get('turbinaId', ''), item.get('componentId', '')]


def _add_gruas_pads_sheet(wb, gruas_data, lang='pt'):
    """Criar sheet de Gruas de Pads"""
    print(f"[DEBUG] _add_gruas_pads_sheet called with {len(gruas_data)} items")
    sheet_name = 'Cranes (Pads)' if lang == 'en' else 'Gruas (Pads)'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    cell_fill = PatternFill(start_color="FFFFFF", end_color="FFFFFF", fill_type="solid")
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers traduzidos
    if lang == 'en':
        headers = [
            'Turbine',
            'Crane Model',
            'Activity Type',
            'Start Date',
            'Start Time',
            'End Date',
            'End Time',
            'Duration',
            'Reason',
            'Origin',
            'Destination',
            'Notes'
        ]
    else:
        headers = [
            'Turbina',
            'Modelo da Grua',
            'Tipo de Atividade',
            'Data Início',
            'Hora Início',
            'Data Fim',
            'Hora Fim',
            'Duração',
            'Motivo',
            'Origem',
            'Destino',
            'Observações'
        ]
    
    # Larguras das colunas
    column_widths = [12, 20, 15, 12, 10, 12, 10, 10, 15, 12, 12, 30]
    
    # ══════════════════════════════════════════════════════════════
    # ESCREVER HEADERS (1 LOOP)
    # ══════════════════════════════════════════════════════════════
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # ══════════════════════════════════════════════════════════════
    # DEFINIR LARGURAS (LOOP SEPARADO)
    # ══════════════════════════════════════════════════════════════
    for col_idx, width in enumerate(column_widths, start=1):
        column_letter = get_column_letter(col_idx)
        ws.column_dimensions[column_letter].width = width
    
    # ══════════════════════════════════════════════════════════════
    # ESCREVER DADOS
    # ══════════════════════════════════════════════════════════════
    for row_idx, item in enumerate(gruas_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('turbinaId', '')).border = border
        ws.cell(row=row_idx, column=2, value=item.get('gruaModelo', '')).border = border
        ws.cell(row=row_idx, column=3, value=translate_tipo(item.get('tipo', ''), lang)).border = border
        ws.cell(row=row_idx, column=4, value=item.get('dataInicio', '')).border = border
        ws.cell(row=row_idx, column=5, value=item.get('horaInicio', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('dataFim', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('horaFim', '')).border = border
        ws.cell(row=row_idx, column=8, value=item.get('duracao', '')).border = border
        ws.cell(row=row_idx, column=9, value=translate_motivo(item.get('motivo', ''), lang)).border = border
        ws.cell(row=row_idx, column=10, value=item.get('origem', '')).border = border
        ws.cell(row=row_idx, column=11, value=item.get('destino', '')).border = border
        ws.cell(row=row_idx, column=12, value=item.get('observacoes', '')).border = border
    
    msg = f"✓ Sheet '{sheet_name}' created with {len(gruas_data)} records" if lang == 'en' else f"✓ Sheet '{sheet_name}' criada com {len(gruas_data)} registros"
    print(msg)


def _add_gruas_gerais_sheet(wb, gruas_data, lang='pt'):
    """Criar sheet de Gruas Gerais"""
    print(f"DEBUG: _add_gruas_gerais_sheet called with {len(gruas_data)} items")
    sheet_name = 'Cranes (General)' if lang == 'en' else 'Gruas Gerais'
    ws = wb.create_sheet(sheet_name)
    
    # Estilos
    header_fill = PatternFill(start_color="70AD47", end_color="70AD47", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    border = Border(
        left=Side(style='thin'),
        right=Side(style='thin'),
        top=Side(style='thin'),
        bottom=Side(style='thin')
    )
    
    # Headers (SEM coluna Turbina, COM coluna Descrição)
    if lang == 'en':
        headers = [
            'Crane Model',
            'Description',
            'Activity Type',
            'Start Date',
            'Start Time',
            'End Date',
            'End Time',
            'Duration',
            'Reason',
            'Origin',
            'Destination',
            'Notes'
        ]
    else:
        headers = [
            'Modelo da Grua',
            'Descrição',
            'Tipo de Atividade',
            'Data Início',
            'Hora Início',
            'Data Fim',
            'Hora Fim',
            'Duração',
            'Motivo',
            'Origem',
            'Destino',
            'Observações'
    ]
    
    # Larguras das colunas
    column_widths = [20, 25, 15, 12, 10, 12, 10, 10, 15, 12, 12, 30]
    
    # ══════════════════════════════════════════════════════════════
    # ESCREVER HEADERS
    # ══════════════════════════════════════════════════════════════
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.value = header
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal='center', vertical='center')
        cell.border = border
    
    # ══════════════════════════════════════════════════════════════
    # DEFINIR LARGURAS
    # ══════════════════════════════════════════════════════════════
    for col_idx, width in enumerate(column_widths, start=1):
        column_letter = get_column_letter(col_idx)
        ws.column_dimensions[column_letter].width = width
    
    # ══════════════════════════════════════════════════════════════
    # ESCREVER DADOS
    # ══════════════════════════════════════════════════════════════
    for row_idx, item in enumerate(gruas_data, start=2):
        ws.cell(row=row_idx, column=1, value=item.get('gruaModelo', '')).border = border
        ws.cell(row=row_idx, column=2, value=item.get('descricao', '')).border = border
        ws.cell(row=row_idx, column=3, value=translate_tipo(item.get('tipo', ''), lang)).border = border
        ws.cell(row=row_idx, column=4, value=item.get('dataInicio', '')).border = border
        ws.cell(row=row_idx, column=5, value=item.get('horaInicio', '')).border = border
        ws.cell(row=row_idx, column=6, value=item.get('dataFim', '')).border = border
        ws.cell(row=row_idx, column=7, value=item.get('horaFim', '')).border = border
        ws.cell(row=row_idx, column=8, value=item.get('duracao', '')).border = border
        ws.cell(row=row_idx, column=9, value=translate_motivo(item.get('motivo', ''), lang)).border = border
        ws.cell(row=row_idx, column=10, value=item.get('origem', '')).border = border
        ws.cell(row=row_idx, column=11, value=item.get('destino', '')).border = border
        ws.cell(row=row_idx, column=12, value=item.get('observacoes', '')).border = border
    
    print(f"✓ Sheet 'Gruas Gerais' criada com {len(gruas_data)} registros")


def translate_tipo(tipo, lang='pt'):
    """Traduzir tipo de atividade"""
    if lang == 'en':
        translations = {
            'mobilizacao': 'Mobilization',
            'trabalho': 'Work',
            'paragem': 'Stoppage',
            'transferencia': 'Transfer',
            'desmobilizacao': 'Demobilization'
        }
    else:  # pt
        translations = {
            'mobilizacao': 'Mobilização',
            'trabalho': 'Trabalho',
            'paragem': 'Paragem',
            'transferencia': 'Transferência',
            'desmobilizacao': 'Desmobilização'
        }
    return translations.get(tipo, tipo)


def translate_motivo(motivo, lang='pt'):
    """Traduzir motivo de paragem"""
    if not motivo:
        return ''
    
    if lang == 'en':
        translations = {
            'wind': 'Wind',
            'mechanical': 'Mechanical Issue',
            'waiting_components': 'Waiting Components',
            'safety': 'Safety'
        }
    else:  # pt
        translations = {
            'wind': 'Vento',
            'mechanical': 'Problema Mecânico',
            'waiting_components': 'Aguardar Componentes',
            'safety': 'Segurança'
        }
    return translations.get(motivo, motivo)


if __name__ == '__main__':
    input_data = json.loads(sys.stdin.read())
    
    project_name = input_data['projectName']
    data_by_phase = input_data['dataByPhase']
    selected_phases = input_data['selectedPhases']
    output_path = input_data['outputPath']
    language = input_data.get('language', 'pt')  # Language parameter
    
    generate_excel_report(project_name, data_by_phase, selected_phases, output_path, language)  # Pass language

