#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PDF Report Generator for As-Built Installation Reports
Generates professional PDF reports with tables and formatting
"""

import sys
import json
import io

# Ensure UTF-8 encoding for stdout on Windows
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from reportlab.lib import colors
from reportlab.lib import colors as rl_colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart, HorizontalBarChart
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from datetime import datetime


# ══════════════════════════════════════════════════════════════════════════
# FUNÇÕES DE CAPA, RESUMO EXECUTIVO, HEADERS E FOOTERS (FASE 1)
# ══════════════════════════════════════════════════════════════════════════

def create_cover_page(story, styles, project_name, language='pt'):
    """
    Criar página de capa profissional
    """
    from datetime import datetime
    
    # Espaço no topo
    story.append(Spacer(1, 80))
    
    # Logo/Título principal
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=28,
        textColor=colors.HexColor('#1F4E78'),
        alignment=1,  # Center
        spaceAfter=12,
        fontName='Helvetica-Bold'
    )
    
    story.append(Paragraph('🏗️ AS-BUILT', title_style))
    
    # Subtítulo
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        fontSize=14,
        textColor=colors.grey,
        alignment=1,
        spaceAfter=30,
    )
    
    subtitle_text = 'RELATÓRIO DE INSTALAÇÃO DE TURBINAS' if language == 'pt' else 'WIND TURBINE INSTALLATION REPORT'
    story.append(Paragraph(subtitle_text, subtitle_style))
    
    # Linha decorativa
    story.append(Spacer(1, 20))
    line_data = [['─' * 80]]
    line_table = Table(line_data, colWidths=[500])
    line_table.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.lightgrey),
    ]))
    story.append(line_table)
    story.append(Spacer(1, 40))
    
    # Nome do Projeto (DESTAQUE)
    project_style = ParagraphStyle(
        'ProjectName',
        fontSize=22,
        textColor=colors.white,
        alignment=1,
        spaceAfter=20,
        fontName='Helvetica-Bold',
        backColor=colors.HexColor('#1F4E78'),
        borderPadding=15,
    )
    
    story.append(Paragraph(f'<b>{project_name}</b>', project_style))
    story.append(Spacer(1, 60))
    
    # Informações do Relatório
    info_style = ParagraphStyle(
        'InfoStyle',
        fontSize=11,
        textColor=colors.HexColor('#1F4E78'),
        alignment=1,
        spaceAfter=8,
    )
    
    date_label = 'Data do Relatório:' if language == 'pt' else 'Report Date:'
    generated_label = 'Gerado por:' if language == 'pt' else 'Generated by:'
    
    story.append(Paragraph(f'<b>{date_label}</b> {datetime.now().strftime("%d/%m/%Y %H:%M")}', info_style))
    story.append(Paragraph(f'<b>{generated_label}</b> As-Built v2.0', info_style))
    
    story.append(Spacer(1, 120))
    
    # Rodapé da capa
    footer_style = ParagraphStyle(
        'FooterStyle',
        fontSize=9,
        textColor=colors.grey,
        alignment=1,
    )
    
    story.append(Paragraph('www.asbuilt.com', footer_style))
    
    # Page break
    story.append(PageBreak())
    
    print("✓ Página de capa criada")


def create_executive_summary(story, styles, project_name, data_by_phase, language='pt'):
    """
    Criar página de resumo executivo
    """
    # Título da secção
    summary_title = 'RESUMO EXECUTIVO' if language == 'pt' else 'EXECUTIVE SUMMARY'
    story.append(Paragraph(summary_title, styles['Heading1']))
    story.append(Spacer(1, 20))
    
    # ══════════════════════════════════════════════════════════════
    # TABELA DE PROGRESSO POR FASE
    # ══════════════════════════════════════════════════════════════
    
    section_style = ParagraphStyle(
        'SectionTitle',
        fontSize=12,
        textColor=colors.HexColor('#1F4E78'),
        fontName='Helvetica-Bold',
        spaceAfter=10,
    )
    
    progress_title = 'Progresso por Fase' if language == 'pt' else 'Progress by Phase'
    story.append(Paragraph(progress_title, section_style))
    
    # Headers
    if language == 'pt':
        headers = ['Fase', 'Total', 'Concluídos', 'Percentagem']
    else:
        headers = ['Phase', 'Total', 'Completed', 'Percentage']
    
    table_data = [headers]
    
    # Nomes das fases
    phase_names = {
        'pt': {
            'recepcao': 'Receção',
            'preparacao': 'Preparação',
            'preAssemblagem': 'Pré-Assemblagem',
            'assemblagem': 'Assemblagem',
            'torqueTensioning': 'Torque & Tensioning',
            'fasesFinais': 'Fases Finais',
        },
        'en': {
            'recepcao': 'Reception',
            'preparacao': 'Preparation',
            'preAssemblagem': 'Pre-Assembly',
            'assemblagem': 'Assembly',
            'torqueTensioning': 'Torque & Tensioning',
            'fasesFinais': 'Final Phases',
        }
    }
    
    # Calcular estatísticas
    for phase_key, phase_data in data_by_phase.items():
        if phase_key in ['gruasPads', 'gruasGerais']:
            continue
        
        phase_name = phase_names.get(language, phase_names['pt']).get(phase_key, phase_key)
        total = len(phase_data)
        completed = sum(1 for item in phase_data if item.get('dataFim'))
        percentage = (completed / total * 100) if total > 0 else 0
        
        table_data.append([
            phase_name,
            str(total),
            str(completed),
            f'{percentage:.1f}%'
        ])
    
    # Criar tabela
    table = Table(table_data, colWidths=[200, 80, 80, 100])
    table.setStyle(TableStyle([
        # Header
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        
        # Dados
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
    ]))
    
    story.append(table)
    story.append(Spacer(1, 30))
    
    # ══════════════════════════════════════════════════════════════
    # ESTATÍSTICAS DE GRUAS
    # ══════════════════════════════════════════════════════════════
    
    if 'gruasPads' in data_by_phase or 'gruasGerais' in data_by_phase:
        gruas_title = 'Estatísticas de Gruas' if language == 'pt' else 'Crane Statistics'
        story.append(Paragraph(gruas_title, section_style))
        
        total_atividades = 0
        if 'gruasPads' in data_by_phase:
            total_atividades += len(data_by_phase['gruasPads'])
        if 'gruasGerais' in data_by_phase:
            total_atividades += len(data_by_phase['gruasGerais'])
        
        stats_text = f"<b>Total de Atividades:</b> {total_atividades}" if language == 'pt' else f"<b>Total Activities:</b> {total_atividades}"
        story.append(Paragraph(stats_text, styles['Normal']))
    
    story.append(PageBreak())
    
    print("✓ Página de resumo executivo criada")


def create_visual_dashboard(story, styles, project_name, data_by_phase, language='pt'):
    """
    Criar dashboard visual com gráficos
    """
    # Título
    title = 'DASHBOARD VISUAL' if language == 'pt' else 'VISUAL DASHBOARD'
    story.append(Paragraph(title, styles['Heading1']))
    story.append(Spacer(1, 20))
    
    # ══════════════════════════════════════════════════════════════
    # PREPARAR DADOS
    # ══════════════════════════════════════════════════════════════
    
    phase_names = {
        'pt': {
            'recepcao': 'Receção',
            'preparacao': 'Preparação',
            'preAssemblagem': 'Pré-Assemblagem',
            'assemblagem': 'Assemblagem',
            'torqueTensioning': 'Torque',
            'fasesFinais': 'Fases Finais',
        },
        'en': {
            'recepcao': 'Reception',
            'preparacao': 'Preparation',
            'preAssemblagem': 'Pre-Assembly',
            'assemblagem': 'Assembly',
            'torqueTensioning': 'Torque',
            'fasesFinais': 'Final Phases',
        }
    }
    
    phases_data = []
    percentages = []
    
    for phase_key, phase_data in data_by_phase.items():
        if phase_key in ['gruasPads', 'gruasGerais']:
            continue
        
        phase_name = phase_names.get(language, phase_names['pt']).get(phase_key, phase_key)
        total = len(phase_data)
        completed = sum(1 for item in phase_data if item.get('dataFim'))
        percentage = (completed / total * 100) if total > 0 else 0
        
        phases_data.append((phase_name, total, completed, percentage))
        percentages.append((phase_name, percentage))
    
    # ══════════════════════════════════════════════════════════════
    # GRÁFICO 1: BARRA HORIZONTAL - PROGRESSO
    # ══════════════════════════════════════════════════════════════
    
    section_title = ParagraphStyle(
        'SectionTitle',
        fontSize=12,
        textColor=rl_colors.HexColor('#1F4E78'),
        fontName='Helvetica-Bold',
        spaceAfter=10,
    )
    
    progress_title = 'Progresso por Fase (%)' if language == 'pt' else 'Progress by Phase (%)'
    story.append(Paragraph(progress_title, section_title))
    
    # Criar gráfico
    drawing = Drawing(500, 200)
    
    bc = HorizontalBarChart()
    bc.x = 120
    bc.y = 20
    bc.height = 150
    bc.width = 350
    
    # Dados
    bc.data = [[p[1] for p in percentages]]
    bc.categoryAxis.categoryNames = [p[0] for p in percentages]
    
    # Estilo
    bc.bars[0].fillColor = rl_colors.HexColor('#4472C4')
    bc.valueAxis.valueMin = 0
    bc.valueAxis.valueMax = 100
    bc.valueAxis.valueStep = 20
    
    # Configurações do eixo
    bc.categoryAxis.labels.boxAnchor = 'e'
    bc.categoryAxis.labels.dx = -5
    bc.categoryAxis.labels.fontSize = 9
    
    bc.valueAxis.labels.fontSize = 9
    
    drawing.add(bc)
    story.append(drawing)
    story.append(Spacer(1, 30))
    
    # ══════════════════════════════════════════════════════════════
    # GRÁFICO 2: PIZZA - STATUS DAS TURBINAS
    # ══════════════════════════════════════════════════════════════
    
    status_title = 'Distribuição por Status' if language == 'pt' else 'Distribution by Status'
    story.append(Paragraph(status_title, section_title))
    
    # Contar status (simplificado)
    total_items = sum(len(pd) for pk, pd in data_by_phase.items() if pk not in ['gruasPads', 'gruasGerais'])
    completed_items = sum(
        sum(1 for item in pd if item.get('dataFim'))
        for pk, pd in data_by_phase.items()
        if pk not in ['gruasPads', 'gruasGerais']
    )
    in_progress = total_items - completed_items
    
    # Criar gráfico de pizza
    drawing2 = Drawing(400, 200)
    
    pie = Pie()
    pie.x = 150
    pie.y = 50
    pie.width = 120
    pie.height = 120
    
    # Dados
    pie.data = [completed_items, in_progress]
    
    # Labels
    if language == 'pt':
        pie.labels = [f'Concluído ({completed_items})', f'Pendente ({in_progress})']
    else:
        pie.labels = [f'Completed ({completed_items})', f'Pending ({in_progress})']
    
    # Cores
    pie.slices[0].fillColor = rl_colors.HexColor('#63BE7B')  # Verde
    pie.slices[1].fillColor = rl_colors.HexColor('#F8696B')  # Vermelho
    
    # Configurações
    pie.slices.strokeWidth = 0.5
    pie.slices.strokeColor = rl_colors.white
    
    drawing2.add(pie)
    story.append(drawing2)
    story.append(Spacer(1, 30))
    
    # ══════════════════════════════════════════════════════════════
    # TABELA DE KPIs
    # ══════════════════════════════════════════════════════════════
    
    kpi_title = 'KPIs Principais' if language == 'pt' else 'Key Performance Indicators'
    story.append(Paragraph(kpi_title, section_title))
    
    # Calcular KPIs
    progresso_geral = (completed_items / total_items * 100) if total_items > 0 else 0
    
    # Headers
    if language == 'pt':
        headers = ['KPI', 'Valor', 'Status']
    else:
        headers = ['KPI', 'Value', 'Status']
    
    kpi_data = [
        headers,
        [
            'Progresso Geral' if language == 'pt' else 'Overall Progress',
            f'{progresso_geral:.1f}%',
            '✅' if progresso_geral >= 50 else '⚠️'
        ],
        [
            'Total de Items' if language == 'pt' else 'Total Items',
            str(total_items),
            '✅'
        ],
        [
            'Items Concluídos' if language == 'pt' else 'Completed Items',
            str(completed_items),
            '✅' if completed_items > 0 else '⏸'
        ],
    ]
    
    # Criar tabela
    kpi_table = Table(kpi_data, colWidths=[200, 100, 80])
    kpi_table.setStyle(TableStyle([
        # Header
        ('BACKGROUND', (0, 0), (-1, 0), rl_colors.HexColor('#1F4E78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), rl_colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        
        # Dados
        ('BACKGROUND', (0, 1), (-1, -1), rl_colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, rl_colors.grey),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [rl_colors.white, rl_colors.lightgrey]),
    ]))
    
    story.append(kpi_table)
    story.append(PageBreak())
    
    print("✓ Dashboard visual criado com gráficos")


def create_deviation_analysis(story, styles, data_by_phase, language='pt'):
    """
    Criar análise de desvios e performance
    """
    title = 'ANÁLISE DE DESVIOS' if language == 'pt' else 'DEVIATION ANALYSIS'
    story.append(Paragraph(title, styles['Heading1']))
    story.append(Spacer(1, 20))
    
    # Texto introdutório
    intro_style = ParagraphStyle(
        'Intro',
        fontSize=10,
        textColor=rl_colors.grey,
        spaceAfter=15,
    )
    
    intro_text = "Esta secção analisa os desvios entre o planeado e o real, identificando áreas de atenção."
    if language == 'en':
        intro_text = "This section analyzes deviations between planned and actual, identifying areas of attention."
    
    story.append(Paragraph(intro_text, intro_style))
    
    # ══════════════════════════════════════════════════════════════
    # ALERTAS E OBSERVAÇÕES
    # ══════════════════════════════════════════════════════════════
    
    section_style = ParagraphStyle(
        'SectionTitle',
        fontSize=12,
        textColor=rl_colors.HexColor('#1F4E78'),
        fontName='Helvetica-Bold',
        spaceAfter=10,
    )
    
    alerts_title = 'Pontos de Atenção' if language == 'pt' else 'Points of Attention'
    story.append(Paragraph(alerts_title, section_style))
    
    # Analisar dados para encontrar problemas
    alerts = []
    
    for phase_key, phase_data in data_by_phase.items():
        if phase_key in ['gruasPads', 'gruasGerais']:
            continue
        
        total = len(phase_data)
        completed = sum(1 for item in phase_data if item.get('dataFim'))
        percentage = (completed / total * 100) if total > 0 else 0
        
        if percentage < 30:
            alert_text = f"⚠️ <b>{phase_key}:</b> Apenas {percentage:.0f}% concluído - Requer atenção urgente"
            if language == 'en':
                alert_text = f"⚠️ <b>{phase_key}:</b> Only {percentage:.0f}% completed - Requires urgent attention"
            alerts.append(alert_text)
        elif percentage < 50:
            alert_text = f"🟡 <b>{phase_key}:</b> {percentage:.0f}% concluído - Monitorizar progresso"
            if language == 'en':
                alert_text = f"🟡 <b>{phase_key}:</b> {percentage:.0f}% completed - Monitor progress"
            alerts.append(alert_text)
    
    if alerts:
        for alert in alerts:
            story.append(Paragraph(alert, styles['Normal']))
            story.append(Spacer(1, 8))
    else:
        no_alerts = "✅ Nenhum ponto de atenção identificado. Projeto dentro do esperado."
        if language == 'en':
            no_alerts = "✅ No points of attention identified. Project on track."
        story.append(Paragraph(no_alerts, styles['Normal']))
    
    story.append(Spacer(1, 20))
    
    # ══════════════════════════════════════════════════════════════
    # RECOMENDAÇÕES
    # ══════════════════════════════════════════════════════════════
    
    recommendations_title = 'Recomendações' if language == 'pt' else 'Recommendations'
    story.append(Paragraph(recommendations_title, section_style))
    
    recommendations = [
        "1. Priorizar fases com progresso inferior a 50%",
        "2. Aumentar recursos nas áreas críticas",
        "3. Monitorizar diariamente as fases em atraso",
        "4. Realizar reunião de alinhamento semanal",
    ]
    
    if language == 'en':
        recommendations = [
            "1. Prioritize phases with progress below 50%",
            "2. Increase resources in critical areas",
            "3. Monitor delayed phases daily",
            "4. Hold weekly alignment meetings",
        ]
    
    for rec in recommendations:
        story.append(Paragraph(rec, styles['Normal']))
        story.append(Spacer(1, 6))
    
    story.append(PageBreak())
    
    print("✓ Análise de desvios criada")


def create_crane_analysis(story, styles, data_by_phase, language='pt'):
    """
    Criar análise detalhada de gruas
    """
    if 'gruasPads' not in data_by_phase and 'gruasGerais' not in data_by_phase:
        return
    
    title = 'ANÁLISE DE GRUAS' if language == 'pt' else 'CRANE ANALYSIS'
    story.append(Paragraph(title, styles['Heading1']))
    story.append(Spacer(1, 20))
    
    section_style = ParagraphStyle(
        'SectionTitle',
        fontSize=12,
        textColor=rl_colors.HexColor('#1F4E78'),
        fontName='Helvetica-Bold',
        spaceAfter=10,
    )
    
    # ══════════════════════════════════════════════════════════════
    # ESTATÍSTICAS GERAIS
    # ══════════════════════════════════════════════════════════════
    
    stats_title = 'Estatísticas Gerais' if language == 'pt' else 'General Statistics'
    story.append(Paragraph(stats_title, section_style))
    
    total_atividades = 0
    atividades_trabalho = 0
    atividades_paragem = 0
    
    for phase_key in ['gruasPads', 'gruasGerais']:
        if phase_key in data_by_phase:
            for item in data_by_phase[phase_key]:
                total_atividades += 1
                tipo = item.get('tipo', '').lower()
                if tipo == 'trabalho':
                    atividades_trabalho += 1
                elif tipo == 'paragem':
                    atividades_paragem += 1
    
    # Tabela de estatísticas
    if language == 'pt':
        headers = ['Métrica', 'Valor']
        rows = [
            ['Total de Atividades', str(total_atividades)],
            ['Atividades de Trabalho', str(atividades_trabalho)],
            ['Atividades de Paragem', str(atividades_paragem)],
            ['Taxa de Utilização', f'{(atividades_trabalho/total_atividades*100):.1f}%' if total_atividades > 0 else '0%'],
        ]
    else:
        headers = ['Metric', 'Value']
        rows = [
            ['Total Activities', str(total_atividades)],
            ['Work Activities', str(atividades_trabalho)],
            ['Stoppage Activities', str(atividades_paragem)],
            ['Utilization Rate', f'{(atividades_trabalho/total_atividades*100):.1f}%' if total_atividades > 0 else '0%'],
        ]
    
    stats_data = [headers] + rows
    
    stats_table = Table(stats_data, colWidths=[250, 150])
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), rl_colors.HexColor('#70AD47')),
        ('TEXTCOLOR', (0, 0), (-1, 0), rl_colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('GRID', (0, 0), (-1, -1), 1, rl_colors.grey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [rl_colors.white, rl_colors.lightgrey]),
    ]))
    
    story.append(stats_table)
    story.append(Spacer(1, 20))
    
    # ══════════════════════════════════════════════════════════════
    # CONCLUSÃO
    # ══════════════════════════════════════════════════════════════
    
    conclusion_title = 'Conclusão' if language == 'pt' else 'Conclusion'
    story.append(Paragraph(conclusion_title, section_style))
    
    taxa_utilizacao = (atividades_trabalho/total_atividades*100) if total_atividades > 0 else 0
    
    if taxa_utilizacao >= 85:
        conclusion = "✅ Excelente taxa de utilização de gruas. Manter o desempenho atual."
        if language == 'en':
            conclusion = "✅ Excellent crane utilization rate. Maintain current performance."
    elif taxa_utilizacao >= 70:
        conclusion = "🟡 Boa taxa de utilização. Identificar oportunidades de melhoria."
        if language == 'en':
            conclusion = "🟡 Good utilization rate. Identify improvement opportunities."
    else:
        conclusion = "⚠️ Taxa de utilização abaixo do ideal. Investigar causas de paragens."
        if language == 'en':
            conclusion = "⚠️ Utilization rate below ideal. Investigate stoppage causes."
    
    story.append(Paragraph(conclusion, styles['Normal']))
    story.append(PageBreak())
    
    print("✓ Análise de gruas criada")


def add_page_header(canvas, doc, project_name, section_name, language='pt'):
    """
    Adicionar header em cada página (chamado automaticamente)
    """
    from datetime import datetime
    
    canvas.saveState()
    
    # Header background
    canvas.setFillColor(colors.HexColor('#1F4E78'))
    canvas.rect(0, doc.pagesize[1] - 60, doc.pagesize[0], 40, fill=True, stroke=False)
    
    # Texto do header
    canvas.setFillColor(colors.white)
    canvas.setFont('Helvetica-Bold', 11)
    canvas.drawString(40, doc.pagesize[1] - 35, f"📁 {project_name}")
    
    canvas.setFont('Helvetica', 9)
    date_str = datetime.now().strftime('%d/%m/%Y %H:%M')
    canvas.drawString(40, doc.pagesize[1] - 50, f"📊 {section_name}  •  {date_str}")
    
    canvas.restoreState()


def add_page_footer(canvas, doc, language='pt'):
    """
    Adicionar rodapé em cada página (chamado automaticamente)
    """
    from datetime import datetime
    
    canvas.saveState()
    
    # Linha decorativa
    canvas.setStrokeColor(colors.lightgrey)
    canvas.setLineWidth(0.5)
    canvas.line(40, 40, doc.pagesize[0] - 40, 40)
    
    # Texto do rodapé
    canvas.setFillColor(colors.grey)
    canvas.setFont('Helvetica', 8)
    
    footer_text = f"Gerado por As-Built v2.0  •  {datetime.now().strftime('%d/%m/%Y %H:%M')}  •  www.asbuilt.com"
    if language == 'en':
        footer_text = f"Generated by As-Built v2.0  •  {datetime.now().strftime('%d/%m/%Y %H:%M')}  •  www.asbuilt.com"
    
    canvas.drawCentredString(doc.pagesize[0] / 2, 25, footer_text)
    
    # Número da página
    page_num = canvas.getPageNumber()
    canvas.drawRightString(doc.pagesize[0] - 40, 25, f"Página {page_num}" if language == 'pt' else f"Page {page_num}")
    
    canvas.restoreState()


# ══════════════════════════════════════════════════════════════════════════
# FUNÇÕES DE TRADUÇÃO (NO TOPO, ANTES DE TUDO)
# ══════════════════════════════════════════════════════════════════════════

def translate_tipo(tipo, language='pt'):
    """Traduzir tipo de atividade"""
    translations = {
        'mobilizacao': 'Mobilização',
        'trabalho': 'Trabalho',
        'paragem': 'Paragem',
        'transferencia': 'Transferência',
        'desmobilizacao': 'Desmobilização'
    }
    return translations.get(tipo, tipo)


def translate_motivo(motivo, language='pt'):
    """Traduzir motivo de paragem"""
    if not motivo:
        return ''
    
    translations = {
        'wind': 'Vento',
        'mechanical': 'Problema Mecânico',
        'waiting_components': 'Aguardar Componentes',
        'safety': 'Segurança'
    }
    return translations.get(motivo, motivo)


# ══════════════════════════════════════════════════════════════════════════
# FUNÇÕES DE GRUAS
# ══════════════════════════════════════════════════════════════════════════

def add_gruas_pads_section(story, styles, gruas_data, language='pt'):
    """Adicionar secção de Gruas de Pads ao PDF"""
    
    print(f"DEBUG: add_gruas_pads_section called with {len(gruas_data) if gruas_data else 0} items")
    
    # Título
    story.append(Paragraph("GRUAS (PADS)", styles['Heading1']))
    story.append(Spacer(1, 12))
    
    if not gruas_data:
        story.append(Paragraph("Nenhuma atividade registada.", styles['Normal']))
        print("[WARN] Nenhuma atividade de Gruas de Pads")
        return
    
    # Preparar dados para tabela
    table_data = [[
        'Turbina',
        'Grua',
        'Tipo',
        'Início',
        'Fim',
        'Duração',
        'Obs'
    ]]
    
    for item in gruas_data:
        obs = item.get('observacoes', '')
        obs_truncated = obs[:30] + '...' if len(obs) > 30 else obs
        
        table_data.append([
            item.get('turbinaId', ''),
            item.get('gruaModelo', ''),
            translate_tipo(item.get('tipo', ''), language),
            f"{item.get('dataInicio', '')} {item.get('horaInicio', '')}",
            f"{item.get('dataFim', '')} {item.get('horaFim', '')}",
            item.get('duracao', ''),
            obs_truncated
        ])
    
    # Criar tabela
    table = Table(table_data, colWidths=[60, 90, 70, 80, 80, 50, 100])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4472C4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
    ]))
    
    story.append(table)
    story.append(Spacer(1, 12))
    
    # Resumo
    total_atividades = len(gruas_data)
    story.append(Paragraph(f"<b>Total de atividades:</b> {total_atividades}", styles['Normal']))
    
    print(f"[OK] Seção 'Gruas (Pads)' adicionada com {total_atividades} registros")


def add_gruas_gerais_section(story, styles, gruas_data, language='pt'):
    """Adicionar secção de Gruas Gerais ao PDF"""
    
    print(f"DEBUG: add_gruas_gerais_section called with {len(gruas_data) if gruas_data else 0} items")
    
    # Título
    story.append(Paragraph("GRUAS GERAIS", styles['Heading1']))
    story.append(Spacer(1, 12))
    
    if not gruas_data:
        story.append(Paragraph("Nenhuma atividade registada.", styles['Normal']))
        print("[WARN] Nenhuma atividade de Gruas Gerais")
        return
    
    # Preparar dados para tabela
    table_data = [[
        'Grua',
        'Descrição',
        'Tipo',
        'Início',
        'Fim',
        'Duração',
        'Obs'
    ]]
    
    for item in gruas_data:
        desc = item.get('descricao', '')
        desc_truncated = desc[:20] + '...' if len(desc) > 20 else desc
        
        obs = item.get('observacoes', '')
        obs_truncated = obs[:30] + '...' if len(obs) > 30 else obs
        
        table_data.append([
            item.get('gruaModelo', ''),
            desc_truncated,
            translate_tipo(item.get('tipo', ''), language),
            f"{item.get('dataInicio', '')} {item.get('horaInicio', '')}",
            f"{item.get('dataFim', '')} {item.get('horaFim', '')}",
            item.get('duracao', ''),
            obs_truncated
        ])
    
    # Criar tabela
    table = Table(table_data, colWidths=[90, 80, 70, 80, 80, 50, 100])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#70AD47')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
    ]))
    
    story.append(table)
    story.append(Spacer(1, 12))
    
    # Resumo
    total_atividades = len(gruas_data)
    story.append(Paragraph(f"<b>Total de atividades:</b> {total_atividades}", styles['Normal']))
    
    print(f"[OK] Seção 'Gruas Gerais' adicionada com {total_atividades} registros")


# ══════════════════════════════════════════════════════════════════════════
# FUNÇÃO PRINCIPAL
# ══════════════════════════════════════════════════════════════════════════

def generate_pdf_report(project_name, data_by_phase, selected_phases, output_path, language='pt'):
    """
    Gera relatório PDF com dados de instalação
    """
    print(f"\n{'='*60}")
    print(f"🚀 INICIANDO GERAÇÃO DE RELATÓRIO PDF - FASE 2")
    print(f"{'='*60}")
    print(f"📁 Projeto: {project_name}")
    print(f"🌍 Idioma: {language.upper()}")
    
    # Criar documento
    doc = SimpleDocTemplate(
        output_path,
        pagesize=landscape(A4),
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=80,  # 🆕 Espaço para header
        bottomMargin=60,  # 🆕 Espaço para footer
    )
    
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1F4E78'),
        spaceAfter=30,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    section_style = ParagraphStyle(
        'SectionTitle',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#4472C4'),
        spaceAfter=12,
        spaceBefore=20,
        fontName='Helvetica-Bold'
    )
    
    story = []
    
    # ══════════════════════════════════════════════════════════════
    # 🆕 CAPA (FASE 1)
    # ══════════════════════════════════════════════════════════════
    create_cover_page(story, styles, project_name, language)
    
    # ══════════════════════════════════════════════════════════════
    # 🆕 RESUMO EXECUTIVO (FASE 1)
    # ══════════════════════════════════════════════════════════════
    create_executive_summary(story, styles, project_name, data_by_phase, language)
    
    # ══════════════════════════════════════════════════════════════
    # 🆕 FASE 2 - DASHBOARD VISUAL E ANÁLISES
    # ══════════════════════════════════════════════════════════════
    create_visual_dashboard(story, styles, project_name, data_by_phase, language)
    create_deviation_analysis(story, styles, data_by_phase, language)
    create_crane_analysis(story, styles, data_by_phase, language)
    
    # ══════════════════════════════════════════════════════════════
    # SECÇÕES DAS FASES
    # ══════════════════════════════════════════════════════════════
    
    # DADOS POR FASE
    phase_names = {
        'recepcao': 'RECEÇÃO / DESCARGA',
        'preparacao': 'PREPARAÇÃO',
        'preAssemblagem': 'PRÉ-ASSEMBLAGEM',
        'assemblagem': 'ASSEMBLAGEM',
        'torqueTensionamento': 'TORQUE & TENSIONING',
        'fasesFinais': 'FASES FINAIS',
    }
    
    for phase in selected_phases:
        phase_data = data_by_phase.get(phase, [])
        
        if not phase_data:
            continue
        
        # Adicionar page break antes de cada secção
        story.append(PageBreak())
        
        # Título da secção
        section_title = Paragraph(phase_names.get(phase, phase.upper()), section_style)
        story.append(section_title)
        
        # Criar tabela (código existente...)
        table_data = _create_phase_table(phase, phase_data)
        
        if table_data:
            table = Table(table_data, repeatRows=1)
            
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E78')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('TEXTCOLOR', (0, 1), (-1, -1), colors.black),
                ('ALIGN', (0, 1), (1, -1), 'LEFT'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 8),
                ('TOPPADDING', (0, 1), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F5F5F5')]),
            ]))
            
            story.append(table)
            story.append(Spacer(1, 0.5*cm))
    
    # ═══════════════════════════════════════════════════════════════
    # SECÇÕES DE GRUAS
    # ═══════════════════════════════════════════════════════════════
    
    print("DEBUG: Processing crane sections")
    
    # Processar Gruas de Pads
    if 'gruasPads' in selected_phases:
        print("DEBUG: 'gruasPads' in selected_phases: True")
        if data_by_phase.get('gruasPads'):
            print("[OK] Adding 'Gruas de Pads' section")
            story.append(PageBreak())
            add_gruas_pads_section(story, styles, data_by_phase['gruasPads'], language)
        else:
            print("[WARN] 'gruasPads' selected but no data found")
    else:
        print("DEBUG: 'gruasPads' NOT in selected_phases")

    # Processar Gruas Gerais
    if 'gruasGerais' in selected_phases:
        print("DEBUG: 'gruasGerais' in selected_phases: True")
        if data_by_phase.get('gruasGerais'):
            print("[OK] Adding 'Gruas Gerais' section")
            story.append(PageBreak())
            add_gruas_gerais_section(story, styles, data_by_phase['gruasGerais'], language)
        else:
            print("[WARN] 'gruasGerais' selected but no data found")
    else:
        print("DEBUG: 'gruasGerais' NOT in selected_phases")
    
    # ███ BUILD COM HEADERS E FOOTERS (FASE 1) ███
    def on_page(canvas, doc_obj):
        """
        Callback para adicionar header e footer em cada página
        Não adiciona em página de capa, apenas nas demais
        """
        # Não adicionar header/footer na capa (página 1)
        if doc_obj.page > 1:
            add_page_header(canvas, doc_obj, project_name, 'Relatório de Instalação', language)
            add_page_footer(canvas, doc_obj, language)
    
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    
    print(f"\n✅ PDF salvo com FASE 2 completa: {output_path}")
    print(f"📊 Dashboard com gráficos adicionado")
    print(f"📈 Análise de desvios incluída")
    print(f"🏗️ Análise de gruas detalhada")
    print(f"{'='*60}\n")


def _create_phase_table(phase, phase_data):
    """Cria dados da tabela para uma fase"""
    
    # (Código existente mantém-se igual)
    if phase == 'recepcao':
        headers = ['Turbina', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Data Descarga', 'Hora']
        columns = ['turbinaId', 'componentId', 'vui', 'serialNumber', 'itemNumber', 'dataDescarga', 'horaDescarga']
    
    elif phase in ['preparacao', 'preAssemblagem', 'assemblagem']:
        headers = ['Turbina', 'Component', 'VUI', 'Serial Number', 'Item Number', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim']
        columns = ['turbinaId', 'componentId', 'vui', 'serialNumber', 'itemNumber', 'dataInicio', 'horaInicio', 'dataFim', 'horaFim']
    
    elif phase == 'torqueTensionamento':
        headers = ['Turbina', 'Conexão', 'Torque Value', 'Torque Unit', 'Tensioning Value', 'Tensioning Unit', 'Data', 'Hora']
        columns = ['turbinaId', 'conexao', 'torqueValue', 'torqueUnit', 'tensioningValue', 'tensioningUnit', 'dataExecucao', 'horaExecucao']
    
    elif phase == 'fasesFinais':
        headers = ['Turbina', 'Fase', 'Data Início', 'Hora Início', 'Data Fim', 'Hora Fim', 'Status']
        columns = ['turbinaId', 'faseName', 'dataInicio', 'horaInicio', 'dataFim', 'horaFim', 'status']
    
    else:
        return None
    
    table_data = [headers]
    
    for item in phase_data:
        row = []
        for col_key in columns:
            value = item.get(col_key, '')
            row.append(str(value) if value else '')
        table_data.append(row)
    
    return table_data


# ══════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    input_data = json.loads(sys.stdin.read())
    
    project_name = input_data['projectName']
    data_by_phase = input_data['dataByPhase']
    selected_phases = input_data['selectedPhases']
    output_path = input_data['outputPath']
    language = input_data.get('language', 'pt')
    
    generate_pdf_report(project_name, data_by_phase, selected_phases, output_path, language)